dist: trusty
language: cpp


script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER
  - cmake --build .
  - ./CppConfHelloWorld


env:
  - COMPILER=g++-6



addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
