dist: trusty
language: cpp
sudo: required


install:
  - ./.travis/install.sh

script:
- ./.travis/run.sh


env:
  - BUILD_TYPE=Release C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9
  - BUILD_TYPE=Release C_COMPILER=gcc-5 CXX_COMPILER=g++-5
  - BUILD_TYPE=Release C_COMPILER=gcc-6 CXX_COMPILER=g++-6
  - BUILD_TYPE=Release C_COMPILER=clang-3.9 CXX_COMPILER=clang++-3.9
  - BUILD_TYPE=Debug C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9
  - BUILD_TYPE=Debug C_COMPILER=gcc-5 CXX_COMPILER=g++-5
  - BUILD_TYPE=Debug C_COMPILER=gcc-6 CXX_COMPILER=g++-6
  - BUILD_TYPE=Debug C_COMPILER=clang-3.9 CXX_COMPILER=clang++-3.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - g++-4.9
      - g++-5
      - g++-6
      - clang++-4.0
